language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs"
before_install:
  - "npm install -g npm@2.1.18"
before_script:
  - "rm -rf node_modules/bigpipe/node_modules/bigpipe.js && npm install bigpipe/bigpipe.js"
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@2.11.x && cat coverage/lcov.info | coveralls"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.8"
    - node_js: "iojs"
notifications:
  irc:
    channels:
      - "irc.freenode.org#bigpipe"
    on_success: change
    on_failure: change
